#!/bin/sh

inputFileName=$1
outputFile=$2

echo $outputFile
echo $inputFileName

mycmd=`ffmpeg -re -i ./uploads/processed/$inputFileName -map 0 -map 0 -c:a aac -c:v libx264 -b:v:0 20000k -b:v:1 20000k -s:v:1 1280x720 -profile:v:1 baseline -profile:v:0 main -bf 1 -keyint_min 120 -g 120 -sc_threshold 0 -b_strategy 0 -ar:a:1 22050 -use_timeline 1 -use_template 1 -window_size 5 -adaptation_sets "id=0,streams=v id=1,streams=a" -f dash ./segments/$outputFile/${outputFile}_out.mpd`

eval $mycmd